---
- name: "install npm"
  become: yes
  apt:
    name: npm
    update_cache: yes
    state: latest

- name: Install nvm
  become: yes
  npm:
    name: nvm
    global: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present