---
- name: "install python for Ansible."
  become: yes
  apt:
    name: python3
    state: latest
    
- name: install nodejs v13.8.0
  become: yes
  command: n 13.8.0

- name: "install npm"
  become: yes
  apt:
    name: npm
    update_cache: yes
    state: latest

- name: Install nvm
  become: yes
  npm:
    name: nvm
    global: yes

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Start PM2 server
  become: true  
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start