---
- name: "install npm"
  become: yes
  apt:
    name: npm
    update_cache: yes
    state: latest

- name: Install nvm
  become: yes
  npm:
    name: nvm
    global: yes

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
    
- name: Start PM2 server
  become: true  
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start