---
- name: "Install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Copy backend to remote
  become: true  
  shell: |
    cd /home/ubuntu

- name: "Move backend folder to /home/ubuntu"
  become: true
  copy:
    src: ./backend
    dest: /home/ubuntu
    remote_src: yes
    mode: '0777'

- name: Start PM2 server
  become: true  
  shell: |
    cd /home/ubuntu
    pm2 start npm --name backend -- start