---
- name: "Copy backend to remote"
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz

- name: "Extract backend"
  shell: |
    tar xvf /home/ubuntu/backend.tar

- name: "Install npm modules"
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    cd backend
    npm i

- name: "Build backend"
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    cd backend
    npm run build

- name: "Run backend"
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    cd backend/dist
    pm2 start main.js