---
- name: "Copy dist backend directory to EC2 server"
  become: yes
  copy:
    src: /home/backend.tar.gz
    dest: /home/ubuntu/backend.tar.gz

- name: prepare binaries
  become: true
  shell: |
    cd /home/ubuntu
    tar xvzf artifact.tar.gz -C .

- name: start server
  become: true
  shell: |
    cd /home/ubuntu
    npm install 
    pm2 stop default
    pm2 start npm --name backend -- start